name: manajemen_pelanggan
description: "Aplikasi Sederhana Untuk Manajemen Pelanggan."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  fl_chart: ^0.66.2 # Library untuk charts dan grafik
  sqflite: ^2.3.2 # Database SQLite untuk Flutter
  path_provider: ^2.1.1 # Untuk mengakses direktori aplikasi
  path: ^1.9.0 # Untuk manipulasi path file
  intl: ^0.19.0 # Untuk format tanggal dan angka
  flutter_neumorphic: ^3.2.0
  provider: ^6.1.1 # State management untuk statistics provider
  image_picker: ^1.0.7 # Untuk pemilihan gambar dari galeri/kamera

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
